name: Deploy Full Stack App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Prepare backend dependencies
        run: |
          cd backend
          npm install

      - name: Upload frontend build with rsync
        uses: appleboy/rsync-action@v0.0.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/build/"
          target: "${{ secrets.FRONTEND_PATH }}"
          delete: true

      - name: Upload backend code with rsync
        uses: appleboy/rsync-action@v0.0.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/"
          target: "${{ secrets.BACKEND_PATH }}"
          delete: true

      - name: Restart backend using PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.BACKEND_PATH }}
            /home/ubuntu/.nvm/versions/node/v18.17.0/bin/pm2 restart 3
